In [238]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from IPython.display import display
from sklearn.metrics import mutual_info_score

### 1. Data importing

In [200]:
df = pd.read_csv('telecom_churn.csv')

In [201]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

### 2. Data Preparation

In [202]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [203]:
df.head().T

                            0      1      2      3      4
state                      KS     OH     NJ     OH     OK
account_length            128    107    137     84     75
area_code                 415    415    415    408    415
international_plan         No     No     No    Yes    Yes
voice_mail_plan           Yes    Yes     No     No     No
number_vmail_messages      25     26      0      0      0
total_day_minutes       265.1  161.6  243.4  299.4  166.7
total_day_calls           110    123    114     71    113
total_day_charge        45.07  27.47  41.38   50.9  28.34
total_eve_minutes       197.4  195.5  121.2   61.9  148.3
total_eve_calls            99    103    110     88    122
total_eve_charge        16.78  16.62   10.3   5.26  12.61
total_night_minutes     244.7  254.4  162.6  196.9  186.9
total_night_calls          91    103    104     89    121
total_night_charge      11.01  11.45   7.32   8.86   8.41
total_intl_minutes       10.0   13.7   12.2    6.6   10.1
total_intl_calls            3      3      5      7      3
total_intl_charge         2.7    3.7   3.29   1.78   2.73
customer_service_calls      1      1      0      2      3
churn                   False  False  False  False  False

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account_length          3333 non-null   int64
 2   area_code               3333 non-null   int64
 3   international_plan      3333 non-null   object
 4   voice_mail_plan         3333 non-null   object
 5   number_vmail_messages   3333 non-null   int64
 6   total_day_minutes       3333 non-null   float64
 7   total_day_calls         3333 non-null   int64
 8   total_day_charge        3333 non-null   float64
 9   total_eve_minutes       3333 non-null   float64
 10  total_eve_calls         3333 non-null   int64
 11  total_eve_charge        3333 non-null   float64
 12  total_night_minutes     3333 non-null   float64
 13  total_night_calls       3333 non-null   int64
 14  total_night_charge      3333 non-null   float64
 15  total_intl_minutes      3333 non-null   float64
 16  total_intl_calls        3333 non-null   int64
 17  total_intl_charge       3333 non-null   float64
 18  customer_service_calls  3333 non-null   int64
 19  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 498.1+ KB

In [205]:
df.isna().sum()

state                     0
account_length            0
area_code                 0
international_plan        0
voice_mail_plan           0
number_vmail_messages     0
total_day_minutes         0
total_day_calls           0
total_day_charge          0
total_eve_minutes         0
total_eve_calls           0
total_eve_charge          0
total_night_minutes       0
total_night_calls         0
total_night_charge        0
total_intl_minutes        0
total_intl_calls          0
total_intl_charge         0
customer_service_calls    0
churn                     0
dtype: int64

In [206]:
df.international_plan = (df.international_plan == 'Yes').astype(int)

In [207]:
df.voice_mail_plan = (df.voice_mail_plan == 'Yes').astype(int)

In [208]:
df.churn = (df.churn == True).astype(int)

In [209]:
(df.churn == 'True').astype(int)

0       0
1       0
2       0
3       0
4       0
       ..
3328    0
3329    0
3330    0
3331    0
3332    0
Name: churn, Length: 3333, dtype: int64

In [210]:
df.head()

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn
0,KS,128,415,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,OH,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,NJ,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,OH,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,OK,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

In [211]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account_length          3333 non-null   int64
 2   area_code               3333 non-null   int64
 3   international_plan      3333 non-null   int64
 4   voice_mail_plan         3333 non-null   int64
 5   number_vmail_messages   3333 non-null   int64
 6   total_day_minutes       3333 non-null   float64
 7   total_day_calls         3333 non-null   int64
 8   total_day_charge        3333 non-null   float64
 9   total_eve_minutes       3333 non-null   float64
 10  total_eve_calls         3333 non-null   int64
 11  total_eve_charge        3333 non-null   float64
 12  total_night_minutes     3333 non-null   float64
 13  total_night_calls       3333 non-null   int64
 14  total_night_charge      3333 non-null   float64
 15  total_intl_minutes      3333 non-null   float64
 16  total_intl_calls        3333 non-null   int64
 17  total_intl_charge       3333 non-null   float64
 18  customer_service_calls  3333 non-null   int64
 19  churn                   3333 non-null   int64
dtypes: float64(8), int64(11), object(1)
memory usage: 520.9+ KB

In [212]:
categorical = list(df.dtypes[df.dtypes == 'object'].index)
categorical

['state']

In [213]:
numerical = df.select_dtypes(include=np.number).columns.tolist()
numerical

['account_length',
 'area_code',
 'international_plan',
 'voice_mail_plan',
 'number_vmail_messages',
 'total_day_minutes',
 'total_day_calls',
 'total_day_charge',
 'total_eve_minutes',
 'total_eve_calls',
 'total_eve_charge',
 'total_night_minutes',
 'total_night_calls',
 'total_night_charge',
 'total_intl_minutes',
 'total_intl_calls',
 'total_intl_charge',
 'customer_service_calls',
 'churn']

### 3. Data Splitting (Validation Framework)

In [214]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1, shuffle= True)
df_train, df_val = train_test_split(df_full_train, test_size=0.25 ,random_state=1, shuffle=True)

In [215]:
len(df), len(df_full_train), len (df_train), len (df_val), len(df_test)

(3333, 2666, 1999, 667, 667)

In [216]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [217]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values


del df_train['churn']
del df_val['churn']
del df_test['churn']

### 4. EDA 'Exploratory Data Analysis'

In [218]:
df_full_train = df_full_train.reset_index(drop=True)

In [219]:
df_full_train.isnull().sum()

state                     0
account_length            0
area_code                 0
international_plan        0
voice_mail_plan           0
number_vmail_messages     0
total_day_minutes         0
total_day_calls           0
total_day_charge          0
total_eve_minutes         0
total_eve_calls           0
total_eve_charge          0
total_night_minutes       0
total_night_calls         0
total_night_charge        0
total_intl_minutes        0
total_intl_calls          0
total_intl_charge         0
customer_service_calls    0
churn                     0
dtype: int64

In [220]:
df_full_train.churn.value_counts()

0    2281
1     385
Name: churn, dtype: int64

In [221]:
df_full_train.churn.mean()

0.1444111027756939

In [223]:
df_full_train[numerical].nunique()

account_length             211
area_code                    3
international_plan           2
voice_mail_plan              2
number_vmail_messages       45
total_day_minutes         1479
total_day_calls            118
total_day_charge          1479
total_eve_minutes         1447
total_eve_calls            117
total_eve_charge          1303
total_night_minutes       1441
total_night_calls          119
total_night_charge         883
total_intl_minutes         159
total_intl_calls            21
total_intl_charge          159
customer_service_calls      10
churn                        2
dtype: int64

In [224]:
df_full_train[categorical].nunique()

state    51
dtype: int64

### 5. Feature Importance

#### Churn Rate

In [227]:
churn_international_plan = df_full_train[df_full_train.international_plan == 1].churn.mean()
churn_international_plan

0.4367816091954023

In [228]:
churn_no_international_plan = df_full_train[df_full_train.international_plan == 0].churn.mean()
churn_no_international_plan

0.11268191268191269

In [230]:
global_churn = df_full_train.churn.mean()
global_churn

0.1444111027756939

In [231]:
global_churn - churn_international_plan

-0.2923705064197084

In [232]:
global_churn - churn_no_international_plan

0.03172919009378122

In [234]:
churn_cst_service = df_full_train[df_full_train.customer_service_calls >= 1].churn.mean()
churn_cst_service

0.1460620525059666

In [235]:
churn_no_cst_service = df_full_train[df_full_train.customer_service_calls < 1].churn.mean()
churn_no_cst_service

0.138353765323993

#### Risk Ratio

In [237]:
for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_churn
    df_group['risk'] = df_group['mean'] / global_churn
    display(df_group)
    print()
    print()

state

           mean  count      diff      risk
state
AK     0.066667     45 -0.077744  0.461645
AL     0.112903     62 -0.031508  0.781818
AR     0.239130     46  0.094719  1.655901
AZ     0.083333     48 -0.061078  0.577056
CA     0.269231     26  0.124820  1.864336
CO     0.152542     59  0.008131  1.056306
CT     0.157895     57  0.013484  1.093370
DC     0.088889     45 -0.055522  0.615527
DE     0.145833     48  0.001422  1.009848
FL     0.127660     47 -0.016752  0.884001
GA     0.152174     46  0.007763  1.053755
HI     0.058824     34 -0.085588  0.407334
IA     0.060606     33 -0.083805  0.419677
ID     0.096774     62 -0.047637  0.670130
IL     0.044444     45 -0.099967  0.307763
IN     0.142857     56 -0.001554  0.989239
KS     0.196429     56  0.052017  1.360204
KY     0.111111     45 -0.033300  0.769408
LA     0.075000     40 -0.069411  0.519351
MA     0.169811     53  0.025400  1.175888
MD     0.240741     54  0.096330  1.667051
ME     0.230769     52  0.086358  1.598002
MI     0.206897     58  0.062485  1.432691
MN     0.169014     71  0.024603  1.170368
MO     0.122449     49 -0.021962  0.847919
MS     0.196078     51  0.051667  1.357779
MT     0.181818     55  0.037407  1.259032
NC     0.142857     56 -0.001554  0.989239
ND     0.109091     55 -0.035320  0.755419
NE     0.090909     44 -0.053502  0.629516
NH     0.170213     47  0.025802  1.178668
NJ     0.245283     53  0.100872  1.698505
NM     0.065217     46 -0.079194  0.451609
NV     0.196078     51  0.051667  1.357779
NY     0.149254     67  0.004843  1.033534
OH     0.161290     62  0.016879  1.116883
OK     0.139535     43 -0.004876  0.966234
OR     0.150000     60  0.005589  1.038701
PA     0.200000     40  0.055589  1.384935
RI     0.078431     51 -0.065980  0.543112
SC     0.229167     48  0.084756  1.586905
SD     0.117647     51 -0.026764  0.814668
TN     0.113636     44 -0.030775  0.786895
TX     0.275862     58  0.131451  1.910255
UT     0.166667     60  0.022256  1.154113
VA     0.064516     62 -0.079895  0.446753
VT     0.087719     57 -0.056692  0.607428
WA     0.220339     59  0.075928  1.525776
WI     0.072727     55 -0.071684  0.503613
WV     0.090909     88 -0.053502  0.629516
WY     0.106061     66 -0.038350  0.734435

### 6. Mutual Information and Correlation

In [239]:
mutual_info_score(df_full_train.state,df_full_train.churn)

0.013741615376543012

In [240]:
df_full_train[numerical].corrwith(df_full_train.churn).abs()

account_length            0.016006
area_code                 0.006031
international_plan        0.274008
voice_mail_plan           0.109294
number_vmail_messages     0.097776
total_day_minutes         0.200082
total_day_calls           0.014284
total_day_charge          0.200084
total_eve_minutes         0.090056
total_eve_calls           0.018048
total_eve_charge          0.090056
total_night_minutes       0.041987
total_night_calls         0.001996
total_night_charge        0.041982
total_intl_minutes        0.071595
total_intl_calls          0.071652
total_intl_charge         0.071566
customer_service_calls    0.216366
churn                     1.000000
dtype: float64

In [243]:
corr = df_full_train.corr()
corr.style.background_gradient(cmap='coolwarm')

In [256]:
churn_day_minutes = df_full_train[df_full_train.total_day_minutes < 4].churn.mean()
churn_day_minutes

0.5

### 7. One Hot Encoding

### 8. Model Training

### 9. Using the model